from pathlib import Path

TESTS_PATH = Path(__file__).parent
TEST_DATA_PATH = TESTS_PATH / "test_data"
TEST_DATA_NOTICE_VALIDATOR_PATH = TEST_DATA_PATH / "notice_validator"
TEST_DATA_NOTICE_VALIDATOR_TEST_PACKAGE = TEST_DATA_NOTICE_VALIDATOR_PATH / "test_repository" / "test_package"
TEST_DATA_NOTICE_VALIDATOR_SPARQL_PATH = TEST_DATA_NOTICE_VALIDATOR_TEST_PACKAGE / "validation" / "sparql"
TEST_DATA_NOTICE_VALIDATOR_RDF_PATH = TEST_DATA_NOTICE_VALIDATOR_TEST_PACKAGE / "output" / "notice" / "notice.ttl"