version: '3.10'

services:
  mw-backend:
    container_name: mw-backend-${ENVIRONMENT}
    build:
      context: ../../
      dockerfile: ./infra/backend/Dockerfile
    networks:
      - proxy-net
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      #### BACKEND rules
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend.rule=Host(`api.mw.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend-secured.rule=Host(`api.mw.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.${ENVIRONMENT}-mw-backend-secured.tls=true"

networks:
  proxy-net:
    external:
      name: proxy-net
