version: "3.10"
services:
  mongodb:
    image: mongo:5.0.10
    container_name: mw-mongodb-${ENVIRONMENT}
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-net
      - common-ext
    ports:
      - ${MONGO_DB_PORT}:27017
    restart: unless-stopped
    labels:
      - 'traefik.enable=false'

  mongo-express:
    image: mongo-express
    container_name: mongo-express-mw-${ENVIRONMENT}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mw-mongodb-${ENVIRONMENT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    networks:
      - mongodb-mw-net
      - proxy-net
    healthcheck:
      test: wget --quiet --tries=3 --spider http://${ME_CONFIG_BASICAUTH_USERNAME}:${ME_CONFIG_BASICAUTH_PASSWORD}@mongo-express-${ENVIRONMENT}:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}.rule=Host(`mongo.mw.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}-secured.rule=Host(`mongo.mw.${SUBDOMAIN}${DOMAIN}`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.mw-mongo-${ENVIRONMENT}-secured.tls=true"


volumes:
  mongodb-data:
    name: mongodb-data-mw-${ENVIRONMENT}

networks:
  mongodb-net:
    internal: false
    name: mongodb-net-mw-${ENVIRONMENT}
  proxy-net:
    external:
      name: proxy-net
  common-ext:
    external:
      name: common-ext-${ENVIRONMENT}
